language: clojure
lein: lein2
before_install:
  - sudo service elasticsearch start
  - sleep 3
  - sudo service elasticsearch status
script: lein2 all test
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
